### ISSUE TITLE
Problem with number format

### ISSUE THREAD

**Issue by cleterrier** [zs6e/excytosis-analyzer-plugin#1]
I get an error with ExoJ 1.51 (current version from [the webpage](https://www.project-exoj.com/), note sure if 1.51 or 1.151?), ImageJ 2.14.0, 1.54i on Java 1.8 in MacOS:

- Open the "test.tif" stack for analysis, then launch ExoJ. Link to the test stack:
https://drive.google.com/file/d/1fgKcmstE1Qii4LxfokQBhhrxTXizT9cf/view?usp=drive_link
- Select the stack in the ExoJ window, click on "Open"
- The following error is displayed and and other window is open:
`Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "20,00"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at ExocytosisAnalyzer.GUI.SecretionParametresWindows.<init>(SecretionParametresWindows.java:287)
	at ExocytosisAnalyzer.GUI.GUIWizard.<init>(GUIWizard.java:100)
	at ExoJ$openImageWin$2.mouseReleased(ExoJ.java:174)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by cleterrier** [comment]
After more testing, I'm getting the same error on a Windows 10 PC, with a freshly installed Fiji. It does not depend on the input stack (I get the same error when using an example stack from Fiji).

**Comment by zs6e** [comment]
This issue is likely caused by the numerical format in French, which results in this problem when there is a "comma" in the numbers. We are working on resolving this issue with "," and ".". As of now, please set Regional formatting of the operating system to English (US for instance).

A version 1.16 has now been released (https://www.project-exoj.com/). We hope this solved the issue!
